# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
    - run: mkdir ../temp
    - run: ls -a
    - run: mv ./.babelrc ./.npmrc ./.github ./.gitignore ../temp
    - run: mv ./* ../temp
    - run: npx create-react-app .
    - run: rm -r src
    - run: mv ../temp/src ../temp/.github .
    - run: rm -r ../temp
    - run: ls src
    - run: ls -a
    - run: git status --ignored
    - run: npm install @react-pdf/renderer --save
    - run: npm run build
    - run: mv build docs
    - run: |
        git config --global user.name 'irik77587'
        git config --global user.email 'irik77587@users.noreply.github.com'
        git commit -am "Automated report"
        git push origin build
